In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
import re

### Dataframes
***

In [24]:
#df_2023 = pd.read_csv('/Users/yasminsarkhosh/Documents/GitHub/machine-learning-bsc-thesis-2024/code/database_miccai_2023.csv', index_col=0, header=0, encoding='utf-8')
#df_2023

In [25]:
df = pd.read_csv('/Users/yasminsarkhosh/Documents/GitHub/machine-learning-bsc-thesis-2024/code/database_miccai_2023.csv', index_col=[0], header=[0], encoding='utf-8')


In [26]:
df.info()

#731 entries, 0 to 730 
#6 columns in total
#title, authors, page numbers, doi, year of publication, part of publication
#dtype: int64(2), object(4)

<class 'pandas.core.frame.DataFrame'>
Index: 731 entries, 0 to 730
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Title                731 non-null    object
 1   Authors              731 non-null    object
 2   Page numbers         731 non-null    object
 3   DOI                  731 non-null    object
 4   Year of publication  731 non-null    int64 
 5   Part of publication  731 non-null    int64 
dtypes: int64(2), object(4)
memory usage: 40.0+ KB


There is a total of 730 papers in MICCAI 2023. However, the dataframe contains 731. Examining the dataframe, 
I will first look into the number of papers by publication (Part of Publication)

In [27]:
df.head()

Title  \
0  PET-Diffusion: Unsupervised PET Enhancement Ba...   
1  MedIM: Boost Medical Image Representation via ...   
2  UOD: Universal One-Shot Detection of Anatomica...   
3  S2^2ME: Spatial-Spectral Mutual Teaching and E...   
4  Modularity-Constrained Dynamic Representation ...   

                                             Authors Page numbers  \
0  Caiwen Jiang, Yongsheng Pan, Mianxin Liu, Lei ...         3-12   
1  Yutong Xie, Lin Gu, Tatsuya Harada, Jianpeng Z...        13-23   
2  Heqin Zhu, Quan Quan, Qingsong Yao, Zaiyi Liu,...        24-34   
3  An Wang, Mengya Xu, Yang Zhang, Mobarakol Isla...        35-45   
4  Qianqian Wang, Mengqi Wu, Yuqi Fang, Wei Wang,...        46-56   

                           DOI  Year of publication  Part of publication  
0  10.1007/978-3-031-43907-0_1                 2023                    1  
1  10.1007/978-3-031-43907-0_2                 2023                    1  
2  10.1007/978-3-031-43907-0_3                 2023                    1  
3  10.1007/978-3-031-43907-0_4                 2023                    1  
4  10.1007/978-3-031-43907-0_5                 2023                    1

In [28]:
# count the number of papers for each publication. There is 10 publications in total

print('Number of papers in Publication 1:', df['Part of publication'].value_counts()[1]) #73
print('Number of papers in Publication 2:', df['Part of publication'].value_counts()[2]) #74
print('Number of papers in Publication 3:', df['Part of publication'].value_counts()[3]) #72
print('Number of papers in Publication 4:', df['Part of publication'].value_counts()[4]) #75
print('Number of papers in Publication 5:', df['Part of publication'].value_counts()[5]) #76
print('Number of papers in Publication 6:', df['Part of publication'].value_counts()[6]) #77
print('Number of papers in Publication 7:', df['Part of publication'].value_counts()[7]) #75
print('Number of papers in Publication 8:', df['Part of publication'].value_counts()[8]) #65
print('Number of papers in Publication 9:', df['Part of publication'].value_counts()[9]) #70
print('Number of papers in Publication 10:', df['Part of publication'].value_counts()[10]) #74

# count the total number of papers in the dataframe
print('Total number of papers:', df['Part of publication'].value_counts().sum()) #731

Number of papers in Publication 1: 73
Number of papers in Publication 2: 74
Number of papers in Publication 3: 72
Number of papers in Publication 4: 75
Number of papers in Publication 5: 76
Number of papers in Publication 6: 77
Number of papers in Publication 7: 75
Number of papers in Publication 8: 65
Number of papers in Publication 9: 70
Number of papers in Publication 10: 74
Total number of papers: 731


In [29]:
# Checking for missing values in the dataset
print(df.loc[df['Part of publication'] == 1].count()) #73
print(df.loc[df['Part of publication'] == 2].count()) #74
print(df.loc[df['Part of publication'] == 3].count()) #72
print(df.loc[df['Part of publication'] == 4].count()) #75
print(df.loc[df['Part of publication'] == 5].count()) #76
print(df.loc[df['Part of publication'] == 6].count()) #77
print(df.loc[df['Part of publication'] == 7].count()) #75
print(df.loc[df['Part of publication'] == 8].count()) #65
print(df.loc[df['Part of publication'] == 9].count()) #70
print(df.loc[df['Part of publication'] == 10].count()) #74

# the number of papers for each publication is equal the number of papers for each publication on the website

Title                  73
Authors                73
Page numbers           73
DOI                    73
Year of publication    73
Part of publication    73
dtype: int64
Title                  74
Authors                74
Page numbers           74
DOI                    74
Year of publication    74
Part of publication    74
dtype: int64
Title                  72
Authors                72
Page numbers           72
DOI                    72
Year of publication    72
Part of publication    72
dtype: int64
Title                  75
Authors                75
Page numbers           75
DOI                    75
Year of publication    75
Part of publication    75
dtype: int64
Title                  76
Authors                76
Page numbers           76
DOI                    76
Year of publication    76
Part of publication    76
dtype: int64
Title                  77
Authors                77
Page numbers           77
DOI                    77
Year of publication    77
Part of publication    77

In [33]:
# Selecting duplicate rows except first
# occurrence based on all columns
duplicate = df[df.duplicated()]
 
print("Duplicate Rows :")
 
# Print the resultant Dataframe
duplicate

Duplicate Rows :


Empty DataFrame
Columns: [Title, Authors, Page numbers, DOI, Year of publication, Part of publication]
Index: []

#### Dataframe: papers with cancer in their title

In [32]:
# selecting papers with cancer in the title, add them into a new dataframe
df_cancer = df.loc[df.Title.str.contains('Cancer', regex=False, na=False)]

print(len(df_cancer)) # 23 papers with cancer in the title

# saving dataframe for papers with cancer in the title
df_cancer.to_csv('/Users/yasminsarkhosh/Documents/GitHub/machine-learning-bsc-thesis-2024/code/database_miccai_2023_cancer.csv', index=True, header=True, encoding='utf-8')

23


In [34]:
title_list = df_cancer["Title"]
author_list = df_cancer["Authors"]

author_list = author_list.to_list()
title_list = title_list.to_list()

In [35]:
print(len(author_list)) #23
print(len(title_list))  #23

23
23


***
### PDFs
***

#### Reading text files

In [ ]:
# glob module to save all the txt files (10 files in total) into a single file text file
#import glob
#read_files = glob.glob("/Users/yasminsarkhosh/Documents/GitHub/machine-learning-bsc-thesis-2024/miccai_2023/*.txt")

#with open("miccai2023_complete_volumen.txt", "wb") as outfile:
#    for f in read_files:
#        with open(f, "rb") as infile:
#            outfile.write(infile.read())

# file is saved in the same directory as the code

In [ ]:
# reading in text file and splitting it into a list of strings
path = '/Users/yasminsarkhosh/Documents/GitHub/machine-learning-bsc-thesis-2024/miccai_2023/others/all-in.txt'
text_data = list()
if os.path.exists(path):
    open_file = open(path, 'r', encoding="utf-8")
    text_data = open_file.read().split('\n')
    text_data = list(filter(None, text_data))

text_data

In [ ]:
# pdfplumber to extract text from pdf
import pdfplumber

with pdfplumber.open("/Users/yasminsarkhosh/Downloads/978-3-031-43987-2_74.pdf") as pdf: 
    for text in pdf.pages:
        normal_text = text.filter(lambda obj: obj["object_type"] == "char")
        print(normal_text.extract_text())

***
### Using the miccai 2023 database (csv file) to split text file of all 730 papers into separate papers
***

In [ ]:
import os
import csv
import PyPDF2
import pandas as pd

In [38]:
csv_file_path = "/Users/yasminsarkhosh/Documents/GitHub/machine-learning-bsc-thesis-2024/databases/database_miccai_2023.csv"  # MICCAI 2023 CSV file
pdf_folder = "/Users/yasminsarkhosh/Documents/GitHub/machine-learning-bsc-thesis-2024/miccai_2023/miccai2023_complete_volumen.txt"  # MICCAI 2023 PDF folder
output_folder = "./output"  # Output folder for saving split papers
os.makedirs(output_folder, exist_ok=True)

#### Making a list of all titles and their page numbers

In [39]:
with open(csv_file_path, 'r') as csv_file: # open the csv file
    df_csv = pd.read_csv(csv_file, index_col=0) # read the csv file into a dataframe

    title_pages = [] # list of strings in the format "(title, page numbers)"

    for pair in zip(df_csv["Title"], df_csv["Page numbers"]): # zip the two lists together
        pair_str = "({})".format(",".join(pair)) # join the pair of strings with a comma
        title_pages.append(pair_str) # append the string to the list

    final_str = ",".join(title_pages)  # join the list of strings with a comma and add a semicolon at the end


print(final_str) # prints (title1,page1),(title2,page2),(title3,page3), (title4,page4),(title5,page5),(title6,page6)...
print(len(title_pages)) # prints 731


(PET-Diffusion: Unsupervised PET Enhancement Based on the Latent Diffusion Model,3-12),(MedIM: Boost Medical Image Representation via Radiology Report-Guided Masking,13-23),(UOD: Universal One-Shot Detection of Anatomical Landmarks,24-34),(S2^2ME: Spatial-Spectral Mutual Teaching and Ensemble Learning for Scribble-Supervised Polyp Segmentation,35-45),(Modularity-Constrained Dynamic Representation Learning for Interpretable Brain Disorder Analysis with Functional MRI,46-56),(Anatomy-Driven Pathology Detection on Chest X-rays,57-66),(VesselVAE: Recursive Variational Autoencoders for 3D Blood Vessel Synthesis,67-76),(Dense Transformer based Enhanced Coding Network for Unsupervised Metal Artifact Reduction,77-86),(Multi-scale Cross-restoration Framework for Electrocardiogram Anomaly Detection,87-97),(Correlation-Aware Mutual Learning for Semi-supervised Medical Image Segmentation,98-108),(TPRO: Text-Prompting-Based Weakly Supervised Histopathology Tissue Segmentation,109-118),(Additional P

error: multiple repeat at position 23114

In [50]:
from glob import glob
import re
# make a pattern, that matches the title and the page numbers
pattern = '\(([^:]+):\s*([^,]+),(\d+)-(\d+)\)'
pattern = re.compile(pattern) # for speeding up 

# get a list of target files
files = glob('/Users/yasminsarkhosh/Documents/GitHub/machine-learning-bsc-thesis-2024/miccai_2023/miccai2023_complete_volumen.txt')
results = list()
# keep track of files without matches
nonmatched = list()

for file in files: 
    # open and access file-content
    with open(file, 'r') as f:
        text_from_file = f.read()
    # search for patterns
    result = re.findall(pattern, text_from_file)
    # append to results only if non-empty 
    # search-result found
    if result:
        results.append(result)
    else:
        nonmatched.append(file)

print(f'Total {len(results)}/{len(files)} files were found with matching results. \nTotal matched cases: { sum([ len(result) for result in results ]) }')

Total 0/1 files were found with matching results. 
Total matched cases: 0
